- name: Install neovim pre-requisites
  shell: sudo apt-get install -y ninja-build gettext cmake unzip curl
- name: Install neovim
  shell: git clone https://github.com/neovim/neovim && cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && git checkout stable && sudo make install && cd ..
